[package]
name = "shooting"
version = "0.1.0"
authors = ["murray501"]
edition = "2018"

# credit
# used sprite images are copied from "Dive Into SpriteKit by Paul Hudson"

[dependencies]
bevy = "0.5.0"
rand = "0.8.3"